// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.DKIMValidator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("selector")]
        public long? Selector { get; set; }

        [JsonProperty("host")]
        public string Host { get; set; }

        [JsonProperty("dkim_host")]
        public string DkimHost { get; set; }

        [JsonProperty("cname_target")]
        public object CnameTarget { get; set; }

        [JsonProperty("has_dkim_record")]
        public bool? HasDkimRecord { get; set; }

        [JsonProperty("dkim_record")]
        public string DkimRecord { get; set; }

        [JsonProperty("dkim_records_count")]
        public long? DkimRecordsCount { get; set; }

        [JsonProperty("version")]
        public string Version { get; set; }

        [JsonProperty("key_type")]
        public string KeyType { get; set; }

        [JsonProperty("key_bits")]
        public long? KeyBits { get; set; }

        [JsonProperty("is_test_mode")]
        public bool? IsTestMode { get; set; }

        [JsonProperty("issues_found")]
        public IssuesFound[] IssuesFound { get; set; }

        [JsonProperty("valid")]
        public bool? Valid { get; set; }

        [JsonProperty("risk_score")]
        public long? RiskScore { get; set; }

        [JsonProperty("risk_level")]
        public string RiskLevel { get; set; }
    }

    public partial class IssuesFound
    {
        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
