// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.DKIMValidator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("dkim_host")]
        public string DkimHost { get; set; }

        [JsonProperty("dkim_record")]
        public string DkimRecord { get; set; }

        [JsonProperty("dkim_records_count")]
        public long DkimRecordsCount { get; set; }

        [JsonProperty("has_dkim_record")]
        public bool HasDkimRecord { get; set; }

        [JsonProperty("host")]
        public string Host { get; set; }

        [JsonProperty("issues_found")]
        public IssuesFound[] IssuesFound { get; set; }

        [JsonProperty("key_type")]
        public string KeyType { get; set; }

        [JsonProperty("selector")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Selector { get; set; }

        [JsonProperty("valid")]
        public bool Valid { get; set; }

        [JsonProperty("version")]
        public string Version { get; set; }
    }

    public partial class IssuesFound
    {
        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }
}
